Update Android SDK build tools
So... at first my build started complaining about Android Studio being
too old:

    KotlinDslScriptsParameter(correlationId=845362774551736, scriptFiles=[]) => StandardKotlinDslScriptsModel(scripts=[], commonModel=CommonKotlinDslScriptModel(classPath=[], sourcePath=[], implicitImports=[]), dehydratedScriptModels={}) - took 0.003 secs

    FAILURE: Build failed with an exception.

    * What went wrong:
    This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.

    * Try:
    Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Exception is:
    com.intellij.openapi.externalSystem.model.ExternalSystemException: This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.
    	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:252)
    	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:127)
    	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:48)
    	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:77)
    	[ 80 exceptions omitted ]
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    java.lang.RuntimeException: This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.
    	at com.android.build.gradle.internal.ide.StudioVersions.verifyStudioIsNotOld(StudioVersions.kt:54)
    	at com.android.build.gradle.internal.ide.StudioVersions.verifyStudioIsNotOld(StudioVersions.kt:34)
    	[ 120 exceptions omitted ]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    	at java.lang.Thread.run(Thread.java:748)

    * Get more help at https://help.gradle.org

    CONFIGURE FAILED in 1s

"Get more help", lol. NO *YOU* need to get help, Android Studio, ffs!
Great! I fucking love timebombs! Good job at mainaining compatibility,
Google! I'm so proud of you!

Well, okay. I didn't have much of a choice here, so I've updated it.

Let's just hope that developers trying out those examples are using the
latest version because that's the only one which is supposed to work, or
so it seems. I guess they are all accustomed to bullying like this.

So... I've updated the IDE and... it started complaining again:

    The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1.
    Android SDK Build Tools 29.0.2 will be used.

So let's update it and see what happens.